name: "AI Security Scanner"
author: "scottman625"
description: "使用 GPT-4 自動檢測代碼中的安全漏洞，並自動上傳 SARIF 報告"

branding:
  icon: "shield"
  color: "blue"

inputs:
  open_ai_key:
    description: "你的 OpenAI API 金鑰"
    required: true
  target_branch:
    description: "要檢測的 Git 分支"
    required: false
    default: "master"

runs:
  using: "composite"
  steps:
    - name: 檢查並獲取最新變更
      shell: bash
      run: |
        echo "Fetching branch: ${{ inputs.target_branch }}"
        git fetch origin ${{ inputs.target_branch }}
        git checkout ${{ inputs.target_branch }}
        git log -1
        if [ $(git rev-list --count HEAD) -gt 1 ]; then
          git diff -p HEAD~1 > changes.diff
        else
          git show HEAD > changes.diff
        fi
        ls -lah changes.diff
        cat changes.diff
        if [ ! -s changes.diff ]; then
          echo "❌ 未偵測到代碼變更，或 git diff 失敗"
          exit 1
        fi

    - name: 確保 `security_report.sarif` 存在
      shell: bash
      run: touch security_report.sarif

    - name: 執行 AI Security Scanner
      shell: bash
      env:
        OPEN_AI_KEY: ${{ inputs.open_ai_key }}
      run: |
        docker run --rm \
          -e OPEN_AI_KEY=$OPEN_AI_KEY \
          -v $(pwd)/changes.diff:/app/changes.diff \
          -v $(pwd)/security_report.sarif:/app/security_report.sarif \
          scottman625/my-security-scanner /app/changes.diff

    - name: 確保 SARIF 報告已生成
      shell: bash
      run: |
        if [ ! -s security_report.sarif ]; then
          echo "❌ Error: SARIF 檔案未生成" && exit 1
        else
          echo "✅ SARIF 報告已成功生成！"
        fi

    - name: 讀取 SARIF 報告（檢查是否包含掃描結果）
      shell: bash
      run: cat security_report.sarif

    - name: 上傳 SARIF 報告作為 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: security_report.sarif

    - name: 上傳至 GitHub Security Alerts
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./security_report.sarif
